### ISSUE TITLE
nginx-proxy cache 적용 시 에러 발생

### ISSUE THREAD

**Issue by ae-chae** [be01-4nd-mini-project-TEAM1/R4-nginx-proxy#4]
### nginx-proxy nGrinder cache 설정 적용 후 테스트에서 에러 발생
![image](https://github.com/be01-4nd-mini-project-TEAM1/R4-nginx-proxy/assets/102152330/cc4c4f3b-e935-4f7b-811d-c0a7487e85bc)

**Comment by ae-chae** [comment]
- cache가 저장되는 경로를 잘못 설정해서 테스트가 불가능했음
- default.conf 파일에서 올바른 경로를 설정
- nGrinder(agent, controller server) 및 proxy server 모두 재부팅 후 해결됨

**Comment by Jaelinny** [comment]
![LGTM](https://i.lgtm.fun/2pd6.gif)
